CREATE TABLE IF NOT EXISTS TB_CATEGORIA_PESSOA (
	CODIGO SERIAL NOT NULL,
	DESCRICAO VARCHAR(45) UNIQUE,
	SIGLA VARCHAR(45) UNIQUE,
	CONSTRAINT PK_CATEGORIA_PESSOA PRIMARY KEY (CODIGO)
);

DROP TABLE IF EXISTS TB_PAPEL_PESSOA CASCADE;

CREATE TABLE IF NOT EXISTS TB_PAPEL_PESSOA (
	CODIGO SERIAL NOT NULL,
	DESCRICAO VARCHAR(45) UNIQUE,
	SIGLA VARCHAR(45) UNIQUE,
	CONSTRAINT PK_PAPEL_PESSOA PRIMARY KEY (CODIGO)
);

DROP TABLE IF EXISTS TB_PESSOA CASCADE;

CREATE TABLE IF NOT EXISTS TB_PESSOA (
	CODIGO SERIAL NOT NULL,
	ID_CATEGORIA_PESSOA INTEGER NOT NULL,
    NOME_COMPLETO VARCHAR(45) NOT NULL,
    LOCALIZACAO VARCHAR(45) NOT NULL,
    IMAGEM BYTEA NULL,
    IS_INSTITUICAO_FINANCEIRA BOOLEAN NOT NULL,
    IS_ATIVO BOOLEAN NOT NULL,
	CONSTRAINT PK_PESSOA PRIMARY KEY (CODIGO),
	CONSTRAINT FK_CATEGORIA_PESSOA FOREIGN KEY (ID_CATEGORIA_PESSOA) REFERENCES TB_CATEGORIA_PESSOA (CODIGO)
);
