INSERT INTO TB_CATEGORIA_PESSOA (CODIGO, DESCRICAO, SIGLA) VALUES
(1, 'Pessoa Física', 'PF'),
(2, 'Pessoa Jurídica', 'PJ'),
(3, 'Pessoa Instituição Financeira', 'PI');

INSERT INTO TB_PAPEL_PESSOA (CODIGO, DESCRICAO, SIGLA) VALUES
(1, 'Administrador Financeiro', 'ADF'),
(2, 'Favorecido', 'FAV'),
(3, 'Contratado', 'COT'),
(4, 'Devedor de Empréstimos', 'DEE');

INSERT INTO TB_PESSOA (CODIGO, ID_CATEGORIA_PESSOA, NOME_COMPLETO, LOCALIZACAO, IMAGEM, IS_INSTITUICAO_FINANCEIRA, IS_ATIVO) VALUES
(1, 1, 'José Quintinn', 'BRASIL', NULL, FALSE, TRUE);

INSERT INTO TB_PESSOA (CODIGO, ID_CATEGORIA_PESSOA, NOME_COMPLETO, LOCALIZACAO, IMAGEM, IS_INSTITUICAO_FINANCEIRA, IS_ATIVO) VALUES
(2, 1, 'Jamille Alves', 'BRASIL', NULL, FALSE, TRUE);

INSERT INTO TB_PESSOA (CODIGO, ID_CATEGORIA_PESSOA, NOME_COMPLETO, LOCALIZACAO, IMAGEM, IS_INSTITUICAO_FINANCEIRA, IS_ATIVO) VALUES
(3, 1, 'Jordann Lucas', 'BRASIL', NULL, FALSE, TRUE);

INSERT INTO TB_PESSOA (CODIGO, ID_CATEGORIA_PESSOA, NOME_COMPLETO, LOCALIZACAO, IMAGEM, IS_INSTITUICAO_FINANCEIRA, IS_ATIVO) VALUES
(4, 1, 'Jonathan Luans', 'BRASIL', NULL, FALSE, TRUE);